ls:
  .js: lowercase | kebabcase
  data:
    .js: pascalcase
  src/components/:
    .dir: pascalcase
    .jsx: pascalcase
  src/pages:
    .jsx: kebabcase
  .storybook:
    .js: lowercase

ignore:
  - .git
  - node_modules
  - .cache
  - public
  - storybook-static
  - .husky
  - dist
  - flow-typed/npm/
